### ISSUE TITLE
Moderation Panel Broken If Reported Question Is Deleted

### ISSUE THREAD

**Issue by thebluecorsair** [Retrospring/bugs#41]
Mainly title.

If a question is reported and then deleted by a moderator and a report still exists for it, it will cause the moderation panel to get a server error (500) and become inaccessible to moderators / administrative team.

**Comment by yukimono** [comment]
Whoops, meant to close it

**Comment by yukimono** [comment]
TODO: run ``rake justask:fix_reports``

**Comment by thebluecorsair** [comment]
The moderation panel is broken again, this time for deleting a comment. I'm so sorry guys D: @yukimono @pixeldesu.

**Comment by yukimono** [comment]
wtffff

**Comment by yukimono** [comment]
i didn't get that error in my local test env

**Comment by yukimono** [comment]
nope i literally just tested it on my local env, tried deleting comments, tried deleting answers, questions, even deleted a user's account record unsafely in pgsql, none of them are making error 500s

**Comment by thebluecorsair** [comment]
Yeah, not quite sure. :cry: Upon deleting a reported comment, the panel seems to be referencing a non-existent comment causing 500 errors.

**Comment by yukimono** [comment]
![screen shot 2015-04-30 at 5 11 53](https://cloud.githubusercontent.com/assets/614231/7403812/7591c85e-eef7-11e4-993e-75da8dae2051.png)

really weird because my env is doing the same but nothing's happening
i'm using the master branch :/

**Comment by yukimono** [comment]
literally the only way i can get this is if i make the user id weird, if the next commit doesn't fix it i have no clue.

**Comment by yukimono** [comment]
the weird part is that i didn't touch comments

**Comment by yukimono** [comment]
I found three additional bugs, which probably caused this.

- When a user is deleted all the reports that are against the user are not marked as deleted
- Comments are not marked as deleted when removed
- It flags the **first** report **of any type** as deleted (This is not always the same target, IDs can overlap)

For example, I have three reports, a report for the question with ID 1, a report for the comment with ID 1, and a report for the user with ID 1, if I delete ANY of the three, only the question report will be flagged as deleted because it **only** checks for the ID, not the ID and the type.

I fixed it in my last commit

**Comment by yukimono** [comment]
In addition to that, if i had five reports all reporting the same id, it would only delete the first report.

**Comment by yukimono** [comment]
reopening incase it gloriously fucks up again

**Comment by yukimono** [comment]
sad part is, because the way it used to mark reports as deleted was monotomous, the only way to properly fix this is to delete every single report.

**Comment by yukimono** [comment]
seems to be okay for now.
