### ISSUE TITLE
Cannot get hyperlink of anonymous questions

### ISSUE THREAD

**Issue by yukimono** [retrospring/bugs#83]
I told 'em Tommy, I tried clicking on the time elapsed but nothin' is happening!

Probably ties in with #66

**Comment by pixeldesu** [comment]
I fixed this issue now, since the only place where you can't access links to anonymous questions is on the profile page.

**Comment by pixeldesu** [comment]
![screenshot - 180215 - 00 08 24](https://cloud.githubusercontent.com/assets/1774242/6239260/5b827c2e-b702-11e4-9cd3-5708e78ef29b.png)

The link to answers is now displayed for every answer on the profile page. We can't link to the question directly, since there is no anonymous user-object and that would throw errors now.
